import Head from 'next/head';
import Link from 'next/link';
import { sanityClient, urlFor } from '../lib/sanity';

const recipesQuery = `*[_type == 'recipe']`;

export default function Home() {
  return (
    <div>
      <Head>
        <title>Intro to Next</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
    </div>
  );
}

export function getStaticProps() {
  return {
    props: {
      data: {
        recipes: [{ title: 'Pineapple Smoothie' }],
      },
    },
  };
}
